disabled_rules: # rule identifiers to exclude from running
  - whitespace
  - line_length
  - trailing_whitespace
  - colon
  - function_body_length
  - type_name

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - BostonFreedomTrailTests
