osx_image: xcode7.3
language: objective-c
before_install:
  - brew update
install:
  - bundle install --without=documentation --path ../travis_bundle_dir
  - bundle exec pod install
  - bundle exec fastlane enable_crash_reporting
script: bundle exec fastlane test
