fastlane_version "2.228.0"

default_platform :ios

platform :ios do
  before_all do
    cocoapods
  end

  desc "Runs all the tests"
  lane :test do
    scan(
      scheme: "BostonFreedomTrail",
      configuration: "Debug",
      clean: true,
      code_coverage: true
    )
  end

  desc "Generate code coverage report"
  lane :coverage do
    xcov(
      workspace: "BostonFreedomTrail.xcworkspace",
      scheme: "BostonFreedomTrail",
      output_directory: "xcov_output",
      minimum_coverage_percentage: 80.0,
      include_test_targets: false
    )
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    gym(scheme: "BostonFreedomTrail")
    pilot
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    gym(scheme: "BostonFreedomTrail")
    deliver(force: true)
  end

  after_all do |lane|

  end

  error do |lane, exception|

  end
end
