fastlane_version "2.146.1"

default_platform :ios

platform :ios do
  before_all do
    cocoapods
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    gym(scheme: "BostonFreedomTrail")
    pilot
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    gym(scheme: "BostonFreedomTrail")
    deliver(force: true)
  end

  after_all do |lane|

  end

  error do |lane, exception|

  end
end
